### PR TITLE
Feature changelog

### PR DESCRIPTION
**Pull request by Abrynos**
Add initial changelog to main page. you may want to move this to a seperated component.

### CODE REVIEW

**Comment by Abrynos** [comment]
tell me if i shall change smth

**Comment by MrBurrBurr** [comment]
Please add `text-decoration: none;` to changelog-link

**Comment by MrBurrBurr** [comment]
Also we can remove now empty `&:hover` and `&:visited`

**Comment by MrBurrBurr** [comment]
Please change `<changelog/>` to `<changelog></changelog>`

**Pull request merged**
